# Generated by Django 3.2.6 on 2022-04-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20220404_0909'),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Meta', to='meta.meta', verbose_name='Meta'),
            preserve_default=False,
        ),
    ]
