# Generated by Django 3.2.12 on 2022-03-26 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('dataInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Inicio')),
                ('dataFim', models.DateTimeField(blank=True, verbose_name='Data Fim')),
                ('todolist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='todolist', to='todolist.todolist', verbose_name='Lista de Tarefa')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
