# Generated by Django 3.2.6 on 2022-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20220404_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='dataFim',
            field=models.DateTimeField(verbose_name='Data Fim'),
        ),
    ]
